### ISSUE TITLE
Ulauncher crash when open preferences menu

### ISSUE THREAD

**Issue by DCR95** [Ulauncher/Ulauncher#1101]
### Environment

Fedora 36

### Bug description

HI,

Ulauncher works normally until I try to access the preferences menu.
When I click the gear to access the preferences ulauncher crashes.

I am using a fresh installation of Fedora 36 with xorg session.

### Log output

```shell
2022-08-01 10:49:03,645 | INFO | ulauncher: main() | Ulauncher version 5.14.4
2022-08-01 10:49:03,645 | INFO | ulauncher: main() | Extension API version 2.0.0
2022-08-01 10:49:03,645 | INFO | ulauncher: main() | GTK+ 3.24.34
2022-08-01 10:49:03,646 | INFO | ulauncher: main() | Is Wayland: False
2022-08-01 10:49:03,646 | INFO | ulauncher: main() | Wayland compatibility: off
2022-08-01 10:49:03,650 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2022-08-01 10:49:03,652 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2022-08-01 10:49:03,652 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2022-08-01 10:49:03,652 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2022-08-01 10:49:03,653 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2022-08-01 10:49:03,653 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2022-08-01 10:49:03,653 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2022-08-01 10:49:03,653 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2022-08-01 10:49:03,653 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2022-08-01 10:49:03,653 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2022-08-01 10:49:03,655 | DEBUG | ulauncher.utils.display: get_screens() | Found 2 monitor(s)
2022-08-01 10:49:03,655 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2022-08-01 10:49:03,655 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 1 - X: 1920, Y: 0, W: 1920, H: 1080
2022-08-01 10:49:03,664 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2022-08-01 10:49:03,666 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
2022-08-01 10:49:03,667 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
2022-08-01 10:49:03,680 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 51 apps in cache
2022-08-01 10:49:03,689 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/evolution-calendar.desktop": constructor returned NULL
2022-08-01 10:49:03,698 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 51 apps in the system
2022-08-01 10:49:03,699 | INFO | ulauncher.search.apps.app_watcher: start() | Scanned desktop dirs in 0.03 seconds
2022-08-01 10:49:03,699 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Primary>space
2022-08-01 10:49:03,702 | DEBUG | ulauncher.search.apps.app_watcher: start() | Start watching desktop files...
2022-08-01 10:49:06,365 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2022-08-01 10:49:06,381 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2022-08-01 10:49:06,381 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
Abandon (core dumped)
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
Thanks for the report. It should be fixed in the latest release, but you can't get that on Fedora quite yet.

See [5.14.7](https://github.com/Ulauncher/Ulauncher/releases/tag/5.14.7) and #1098

**Comment by DCR95** [comment]
That's work fine.
I am waiting for the next release.

**Comment by thorrrr** [comment]
Still does not work down grading for me

**Comment by friday** [comment]
Closing as a duplicate of #1098. If you're on Fedora the maintainer posted a link to a working Ulauncher [5.14.7](https://github.com/Ulauncher/Ulauncher/releases/tag/5.14.7) RPM which runs with any  webkit2gtk3 version. This should hit the main repos eventually, but the next webkit2gtk3 release should fix this also.

**Comment by thorrrr** [comment]
Hey do you guys supply a rpm version for Fedora?
Also a dnf install i still see Ulauncher 5.14 will this work now  or is there an easier way to install 5.14. on Fedora?

Installing:
 ulauncher                               noarch                5.14.4-1.fc36                     updates                1.5 M
Installing dependencies:
 libdbusmenu                             x86_64                16.04.0-19.fc36                   fedora                 134 k
 libdbusmenu-gtk3                        x86_64                16.04.0-19.fc36                   fedora                  40 k
 libindicator-gtk3                       x86_64                12.10.1-22.fc36                   fedora                  66 k
 python3-Levenshtein                     x86_64                0.12.0-20.fc36                    fedora                  80 k
 python3-inotify                         noarch                0.9.6-26.fc36                     fedora                  52 k
 python3-websocket-client                noarch                1.3.2-2.fc36                      updates                 92 k
 wmctrl                                  x86_64                1.07-32.fc36                      fedora                  35 k
Installing weak dependencies:
 libappindicator-gtk3                    x86_64                12.10.0-32.fc36                   fedora                  41 k
