### ISSUE TITLE
Ulauncher service fails to start on login, although it does `restart` fine.

### ISSUE THREAD

**Issue by iago-lito** [Ulauncher/Ulauncher#1254]
### Environment

`$ neofetch --off :: OS: Arch Linux x86_64 Host: Precision 3460 Kernel: 6.4.8-arch1-1 Uptime: 14 hours, 50 mins Packages: 1253 (pacman) Shell: zsh 5.9 Resolution: 2560x1440 DE: GNOME 44.3 WM: Mutter WM Theme: Adwaita Theme: Adwaita [GTK2/3] Icons: Adwaita [GTK2/3] Terminal: alacritty CPU: 12th Gen Intel i7-12700 (20) @ 4.800GHz GPU: NVIDIA T400 4GB GPU: Intel AlderLake-S GT1 Memory: 6713MiB / 31787MiB`

### Bug description

I have installed [`ulauncher-git`](https://aur.archlinux.org/packages/ulauncher-git) from AUR and configured it for startup with:
```sh
$ paru -S ulauncher-git
$ systemctl --user enable --now ulauncher
```
I also ticked this box in ulauncher interface:

- [x] Launch at login

But ulauncher fails to start on reboot, at login, although it does start fine if I either:
- manually click it from the desktop entry
- manually issue `$ ulauncher` from a terminal.
- manually `systemctl --user restart ulauncher`

The stacktrace I'm getting on startup yields `RuntimeError: Gtk couldn't be initialized.`, full stacktrace below.

### Log output

```shell
$ ulauncher --version
Ulauncher 6.0.0

$ journal --user -u ulauncher
-- Boot f4b40c1c307840a498ce3f593193fe3d --
Aug 08 08:42:37 copak systemd[2213]: Started Linux Application Launcher.
Aug 08 08:42:38 copak ulauncher[2308]: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Aug 08 08:42:40 copak ulauncher[2308]: 2023-08-08 08:42:40,231 ⚠️  WARNING Extension Timer has not yet been updated to support API v3.0. It might fail to start or not be fully functional. ExtensionManifest.check_compatibility:153
Aug 08 08:42:40 copak ulauncher[2308]: 2023-08-08 08:42:40,367 ⚠️  WARNING Extension Unicode extension has not yet been updated to support API v3.0. It might fail to start or not be fully functional. ExtensionManifest.check_compatibility:153
Aug 08 08:42:40 copak ulauncher[2308]: 2023-08-08 08:42:40,503 ⚠️  WARNING Extension Process Killer has not yet been updated to support API v3.0. It might fail to start or not be fully functional. ExtensionManifest.check_compatibility:153
Aug 08 08:42:40 copak ulauncher[2308]: 2023-08-08 08:42:40,508 ⚠️  ERROR Extension "com.github.zensoup.ulauncher-unicode" exited instantly with code 1 ExtensionRunner.handle_wait:131
Aug 08 08:42:40 copak ulauncher[2308]: 2023-08-08 08:42:40,508 ⚠️  ERROR Extension "com.github.zensoup.ulauncher-unicode" failed with an error: Traceback (most recent call last): ExtensionRunner.handle_wait:135
Aug 08 08:47:13 copak ulauncher[2308]: 2023-08-08 08:47:13,620 ⚠️  ERROR Uncaught exception main.except_hook:80
Aug 08 08:47:13 copak ulauncher[2308]: Traceback (most recent call last):
Aug 08 08:47:13 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/UlauncherApp.py", line 61, in do_activate
Aug 08 08:47:13 copak ulauncher[2308]:     self.show_launcher()
Aug 08 08:47:13 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/UlauncherApp.py", line 105, in show_launcher
Aug 08 08:47:13 copak ulauncher[2308]:     self.window = UlauncherWindow(application=self)
Aug 08 08:47:13 copak ulauncher[2308]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 08 08:47:13 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 80, in __init__
Aug 08 08:47:13 copak ulauncher[2308]:     super().__init__(
Aug 08 08:47:13 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/LayerShell.py", line 34, in __init__
Aug 08 08:47:13 copak ulauncher[2308]:     super().__init__(*args, **kwargs)
Aug 08 08:47:13 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/gi/overrides/Gtk.py", line 519, in __init__
Aug 08 08:47:13 copak ulauncher[2308]:     raise RuntimeError(
Aug 08 08:47:13 copak ulauncher[2308]: RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
Aug 08 08:50:18 copak ulauncher[2308]: 2023-08-08 08:50:18,756 ⚠️  ERROR Uncaught exception main.except_hook:80
Aug 08 08:50:18 copak ulauncher[2308]: Traceback (most recent call last):
Aug 08 08:50:18 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/UlauncherApp.py", line 61, in do_activate
Aug 08 08:50:18 copak ulauncher[2308]:     self.show_launcher()
Aug 08 08:50:18 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/UlauncherApp.py", line 105, in show_launcher
Aug 08 08:50:18 copak ulauncher[2308]:     self.window = UlauncherWindow(application=self)
Aug 08 08:50:18 copak ulauncher[2308]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 08 08:50:18 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 80, in __init__
Aug 08 08:50:18 copak ulauncher[2308]:     super().__init__(
Aug 08 08:50:18 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/LayerShell.py", line 34, in __init__
Aug 08 08:50:18 copak ulauncher[2308]:     super().__init__(*args, **kwargs)
Aug 08 08:50:18 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/gi/overrides/Gtk.py", line 519, in __init__
Aug 08 08:50:18 copak ulauncher[2308]:     raise RuntimeError(
Aug 08 08:50:18 copak ulauncher[2308]: RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
Aug 08 08:50:21 copak ulauncher[2308]: 2023-08-08 08:50:21,216 ⚠️  ERROR Uncaught exception main.except_hook:80
Aug 08 08:50:21 copak ulauncher[2308]: Traceback (most recent call last):
Aug 08 08:50:21 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/UlauncherApp.py", line 61, in do_activate
Aug 08 08:50:21 copak ulauncher[2308]:     self.show_launcher()
Aug 08 08:50:21 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/UlauncherApp.py", line 105, in show_launcher
Aug 08 08:50:21 copak ulauncher[2308]:     self.window = UlauncherWindow(application=self)
Aug 08 08:50:21 copak ulauncher[2308]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 08 08:50:21 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 80, in __init__
Aug 08 08:50:21 copak ulauncher[2308]:     super().__init__(
Aug 08 08:50:21 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/LayerShell.py", line 34, in __init__
Aug 08 08:50:21 copak ulauncher[2308]:     super().__init__(*args, **kwargs)
Aug 08 08:50:21 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/gi/overrides/Gtk.py", line 519, in __init__
Aug 08 08:50:21 copak ulauncher[2308]:     raise RuntimeError(
Aug 08 08:50:21 copak ulauncher[2308]: RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
Aug 08 08:50:22 copak ulauncher[2308]: 2023-08-08 08:50:22,700 ⚠️  ERROR Uncaught exception main.except_hook:80
Aug 08 08:50:22 copak ulauncher[2308]: Traceback (most recent call last):
Aug 08 08:50:22 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/UlauncherApp.py", line 61, in do_activate
Aug 08 08:50:22 copak ulauncher[2308]:     self.show_launcher()
Aug 08 08:50:22 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/UlauncherApp.py", line 105, in show_launcher
Aug 08 08:50:22 copak ulauncher[2308]:     self.window = UlauncherWindow(application=self)
Aug 08 08:50:22 copak ulauncher[2308]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 08 08:50:22 copak ulauncher[2308]:   File "/usr/lib/python3.11/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 80, in __init__
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment]
I think this should fix it. Let me know if not

And thanks again for another detailed issue report 🙏

**Comment by iago-lito** [comment]
And thank you for supporting Ulauncher <3
I would be glad to try, but I have trouble getting the latest commits from the [AUR package](https://aur.archlinux.org/packages/ulauncher-git). Do you happen to know how long it needs to get there? Or are you familiar with the process?

**Comment by friday** [comment]
> And thank you for supporting Ulauncher <3
> I would be glad to try, but I have trouble getting the latest commits from the [AUR package](https://aur.archlinux.org/packages/ulauncher-git). Do you happen to know how long it needs to get there? Or are you familiar with the process?

The ulauncher-git aur just points to the main branch, so it's by definition always up to date. That's how aur repos named with -git or -dev should work (it's a documented convention in the arch wiki).

But when you build them because they don't bump the version you end up using a cached build. You need to pass a flag to not do that.

yay -S ulauncher-git --answerclean All or paru -S ulauncher-git --rebuild

**Comment by friday** [comment]
I did manage to replicate and test this myself though, so I do think it should work.

**Comment by iago-lito** [comment]
> The ulauncher-git aur just points to the main branch, so it's by definition always up to date.

Well, it seems that the connection has been lost for a while then. I still can't get the updates :(

```sh
$ paru -S ulauncher-git --rebuild # Runs fine, but..

$ cd ~/.cache/paru/clone/ulauncher-git 

$ git log -1 # That's quite an old commit, right?
commit c3477e0236a8728a8db37e970f27fa5fa1a7af57 (HEAD -> master, origin/master, origin/HEAD)
Author: Albin Larsson <mail@albinlarsson.com>
Date:   Wed Dec 28 02:45:13 2022 +0100

    update desktop entry file name (app id)

$ git pull origin master # But it seems there is nothing more on AUR's repo :(
From https://aur.archlinux.org/ulauncher-git
 * branch            master     -> FETCH_HEAD
Already up to date.
```

For some reason, it seems that the new commits are not actually transfered to aur.archlinux.org. Is that supposed to be automatic?

(oh, and maybe this deserved another issue, here or [there](https://aur.archlinux.org/packages/ulauncher-git)?)

**Comment by friday** [comment]
No, just ignore that. You have the latest version installed now. Just do `cat /usr/lib/systemd/user/ulauncher.service` and you will see that it has the new line with `After`.

**Comment by iago-lito** [comment]
Oh indeed, there is a bare repo inside that one: `~/.cache/paru/clone/ulauncher-git/ulauncher`, which actually __*is*__ up-to-date :) And I do see the line with `After` now in the `.service` entry. I'll check that the start succeeds when I restart my machine tomorrow, but we should be good. Thanks again <3

**Comment by friday** [comment]
Yeah, exactly. paru handles it like that. I think you can also ignore the `--rebuild` argument. For paru I don't need it anymore at least.
