### ISSUE TITLE
EOFError when typing in input field after Arch and Ulauncher upgrade

### ISSUE THREAD

**Issue by kuon** [Ulauncher/Ulauncher#260]
After upgrading archlinux and ulauncher, I got the following error log and ulauncher is non operational. Each time I input a letter, the EOFError stack trace is produced in the logs.

```
ulauncher: 4.1.0.r1
archlinux: Linux yoda 4.17.6-1-ARCH #1 SMP PREEMPT Wed Jul 11 19:14:29 UTC 2018 x86_64 GNU/Linux
```

Full logs:
https://gist.github.com/kuon/d5d26c8e00f7727dca50cc73522311b7

**Comment by kuon** [comment]
I deleted my `.cache` folder and the issue was fixed.

But I still think something must be done to avoid the upgrade to break things. Maybe delete the cache on upgrade?

**Comment by gornostal** [comment]
Looks like one of the cache files was corrupted. Usually upgrade goes without any issues.

**Comment by gornostal** [comment]
Will try to reproduce with Arch upgrade

**Comment by gornostal** [comment]
I wasn't able to reproduce it. 
No solution yet.

**Comment by louisch** [comment]
I had a similar error (for me, nothing was appearing in the query list, and I got this error every time I typed):
```
2019-10-28 10:49:51,695 | ERROR | ulauncher: except_hook() | Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ulauncher/ui/windows/UlauncherWindow.py", line 168, in on_input_key_press_event
    Search.get_instance().on_key_press_event(widget, event, self._get_user_query())
  File "/usr/lib/python3.7/site-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/ulauncher/search/Search.py", line 18, in get_instance
    file_browser_mode = FileBrowserMode()
  File "/usr/lib/python3.7/site-packages/ulauncher/search/file_browser/FileBrowserMode.py", line 20, in __init__
    self._file_queries = FileQueries.get_instance()  # type: FileQueries
  File "/usr/lib/python3.7/site-packages/ulauncher/utils/decorator/singleton.py", line 19, in wrapper
    instance = fn(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/ulauncher/search/file_browser/FileQueries.py", line 19, in get_instance
    db.open()
  File "/usr/lib/python3.7/site-packages/ulauncher/utils/db/KeyValueDb.py", line 35, in open
    self.set_records(pickle.load(_in))
```

I fixed it by deleting the files in ~/.local/share/ulauncher, which seemed to be the database files, which made the query list display again.
The errors still happened though, which stopped after I deleted the ulauncher folders in the ~/.cache folder.
I would suggest that a better error message indicating which file is the origin of the corrupted data would allow users to self-diagnose and repair this problem themselves.

**Comment by KuenzelIT** [comment]
I'm having the same issue, but deleting all ulauncher folders in ~/.cache does not work.

Having these issues after updating a bunch of packages and the kernel.

**Comment by KuenzelIT** [comment]
After deleting the files in `$HOME/.local/share/ulauncher` and reinstalling, its working again.

**Comment by gornostal** [comment]
The fix is released with Ulauncher v5.6.0
