### ISSUE TITLE
Ulauncher-toggle not working in 5.9.0

### ISSUE THREAD

**Issue by Surendrajat** [Ulauncher/Ulauncher#642]
This commit eeea80d4cc94918da317192360bf9fafa1803450 breaks it.

### Steps to reproduce
1. Install Ulauncher
2. run `ulauncher-toggle`

### Current behavior

```bash
$ ulauncher-toggle                                                                                                                                          ✔ 
zsh: /usr/bin/ulauncher-toggle: bad interpreter: /usr/bin/sh: no such file or directory
```

### Expected behavior

Ulauncher should show up.

### Environment
**Ulauncher version**: 5.9.0
**Linux distro**: elementary OS 5.1.7 (Ubuntu 18.04)
**Desktop environment**: Pantheon DE

### Logs
Added ^

**Comment by gornostal** [comment]
As a temporary workaround, change the first line of `/usr/bin/ulauncher-toggle` to `#!/bin/sh`

I accidentally introduced this bug yesterday trying to fix a build for Fedora. Didn't realize not all OSes have `/usr/bin/sh`. Sorry about that.

Also, I can't merge your PR, because the Fedora build will be broken then. Thinking how to fix this properly...

**Comment by Surendrajat** [comment]
That's fine. I already fixed it with `/usr/bin/env sh` as you can see in the PR.

According to a few articles and stackoverflow answers, `/usr/bin/env` is fairly portable. Did you try that too?

**Comment by gornostal** [comment]
Yes, I did. It didn't work

**Comment by troycurtisjr** [comment]
@gornostal I'm curious about the original change to /usr/bin/sh, shouldn't Fedora automatically mangle /bin/* to /usr/bin/* in shebang lines? 

```
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
mangling shebang in /usr/bin/ulauncher-toggle from /bin/sh to #!/usr/bin/sh
```
From the 5.8.1 build ^^

**Comment by gornostal** [comment]
@troycurtisjr yes. It does exactly that. But I re-built a Docker image for Fedora and `brp-mangle-shebangs` started failing for some weird reason.
I haven't found a good solution to this issue yet.

**Comment by kam193** [comment]
Hi guys, the issue is still existing. Dou you have an idea how to fix it?

**Comment by tobika** [comment]
After the new update I had again this problem. For me the binary of `sh` resolved correctly via:
`#!/bin/sh`

Not sure how to make this work for everybody?

**Comment by friday** [comment]
This is now fixed in Ulauncher 5.12.0
